version: '3.8'
services:
  redis:
    image: redis:7.2
    restart: always
    ports:
      - 6379:6379

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mevshare:
    build: ./mev-share-node
    volumes:
      - ./builders.yaml:/app/builders.yaml
    ports:
      - 8080:8080
    environment:
      SIMULATION_ENDPOINTS: http://builder:8545
      ETH_ENDPOINT: http://builder:8545
      REDIS_ENDPOINT: redis://redis:6379
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable

  builder:
    build: ./builder
    ports:
      - ${EC_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${EC_PORT_P2P:-30303}:30303/udp # P2P UDP
      - ${EC_PORT_HTTP:-8545}:8545 # JSON-RPC
    restart: always
    command: |
      --goerli
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts="*"
      --http.api="admin,debug,web3,eth,txpool,personal,miner,net,builder,engine"
      --authrpc.jwtsecret="/root/jwt/jwt.hex"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts="*"
      --builder=true
      --builder.remote_relay_endpoint=https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net
      --miner.extradata=${BUILDER_EXTRA_DATA}
      --miner.etherbase=${BUILDER_ADDRESS}
    volumes:
      - ./data/geth:/root/.ethereum
      - ./data/jwt:/root/jwt

  beacon:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-v4.5.0}
    ports:
      - ${CC_PORT_P2P:-9000}:9000/tcp # P2P TCP
      - ${CC_PORT_P2P:-9000}:9000/udp # P2P UDP
      - ${CC_PORT_HTTP:-5052}:5052 # HTTP API
    command: |
      lighthouse bn
      --network=${ETH2_NETWORK:-goerli}
      --checkpoint-sync-url=${CC_CHECKPOINT_SYNC_URL:-https://sync-goerli.beaconcha.in}
      --execution-endpoint=${CC_EXECUTION_ENDPOINT:-http://builder:8551}
      --execution-jwt=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --debug-level=info
      --http
      --http-address=0.0.0.0
      --http-port=5052
    volumes:
      - ./data/lighthouse:/opt/app/beacon
      - ./data/jwt:/opt/jwt
    restart: unless-stopped